serverAddr = "8.162.14.1"
serverPort = 7000
loginFailExit = true

[auth]
token = "cm8P5syfmA40stKGKbj7"

[[proxies]]
name = "device_b_ssh"
type = "xtcp"
localIP = "127.0.0.1"
localPort = 22
secretKey = "device-b-ssh-secret"

[[proxies]]
name = "device_b_desktop"
type = "xtcp"
localIP = "127.0.0.1"
localPort = 3389
secretKey = "device-b-rdp-secret"

[[visitors]]
name = "visit_a_ssh"
type = "stcp"
serverName = "device_a_ssh"
secretKey = "device-a-ssh-secret"
bindAddr = "127.0.0.1"
bindPort = 6000

[[visitors]]
name = "visit_a_rdp"
type = "stcp"
serverName = "device_a_rdp"
secretKey = "device-a-rdp-secret"
bindAddr = "127.0.0.1"
bindPort = 63389
[[proxies]]
name = "tcp_6633"
type = "tcp"
localIP = "127.0.0.1"
localPort = 6633
remotePort = 0

[[proxies]]
name = "toll_box"
type = "tcp"
localIP = "127.0.0.1"
localPort = 8088
remotePort = 0
