serverAddr = "8.162.14.1"
serverPort = 7000
loginFailExit = true

[auth]
token = "cm8P5syfmA40stKGKbj7"

[[visitors]]
name = "mac_visit_toolbox"
type = "xtcp"
serverName = "toolbox_p2p"
secretKey = "toolbox-p2p-secret"
bindAddr = "127.0.0.1"
bindPort = 2088


[[visitors]]
name = "mac_visit_toolbox_file"
type = "xtcp"
serverName = "toolbox_file_p2p"
secretKey = "toolbox-file-p2p-secret"
bindAddr = "127.0.0.1"
bindPort = 1088

[[visitors]]
name = "mac_visit_device_b_ssh"
type = "xtcp"
serverName = "device_b_ssh"
secretKey = "device-b-ssh-secret"
bindAddr = "127.0.0.1"
bindPort = 6001



[[proxies]]
name = "mac_tcp_6633"
type = "tcp"
localIP = "127.0.0.1"
localPort = 6633
remotePort = 0

[[proxies]]
name = "mac_toll_box"
type = "tcp"
localIP = "127.0.0.1"
localPort = 8088
remotePort = 0
