// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {dl} from '../models';
import {frp} from '../models';
import {download} from '../models';
import {system} from '../models';

export function CancelDl(arg1:string):Promise<void>;

export function CancelFrpcDownload():Promise<void>;

export function CheckFrpcInstalled():Promise<boolean>;

export function CheckSettingsFiles():Promise<main.SettingsFileStatus>;

export function ChooseDirectory(arg1:string):Promise<string>;

export function ChooseFile(arg1:string):Promise<string>;

export function DownloadFrpc(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function GetDlProgress(arg1:string):Promise<dl.ProgressInfo>;

export function GetDownloadProgress():Promise<number>;

export function GetDownloadTarget(arg1:string,arg2:string,arg3:string):Promise<main.DownloadTarget>;

export function GetFrpHelp(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetFrpLogs(arg1:number):Promise<string>;

export function GetFrpStatus():Promise<frp.FrpStatus>;

export function GetFrpVersions():Promise<Array<string>>;

export function GetFrpcVersion():Promise<string>;

export function GetMirrors():Promise<Array<download.Mirror>>;

export function GetSettings():Promise<main.AppSettings>;

export function GetSystemInfo():Promise<system.SystemInfo>;

export function KillFrpcProcesses(arg1:Array<number>):Promise<void>;

export function ListDl():Promise<Array<dl.TaskInfo>>;

export function ListFrpcProcesses():Promise<frp.FrpcProcessInfo>;

export function ReadConfig():Promise<string>;

export function RemoveCompletedDl():Promise<void>;

export function ResetSettings():Promise<main.AppSettings>;

export function RestartFrp():Promise<void>;

export function SaveSettings(arg1:main.AppSettings):Promise<main.AppSettings>;

export function StartDl(arg1:string,arg2:string,arg3:number):Promise<string>;

export function StartFrp():Promise<void>;

export function StopFrp():Promise<void>;

export function ValidateConfig():Promise<string>;

export function WriteConfig(arg1:string):Promise<void>;
