// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckFrpcInstalled() {
  return window['go']['main']['App']['CheckFrpcInstalled']();
}

export function ChooseDirectory(arg1) {
  return window['go']['main']['App']['ChooseDirectory'](arg1);
}

export function DownloadFrpc(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DownloadFrpc'](arg1, arg2, arg3, arg4);
}

export function GetDownloadProgress() {
  return window['go']['main']['App']['GetDownloadProgress']();
}

export function GetFrpLogs(arg1) {
  return window['go']['main']['App']['GetFrpLogs'](arg1);
}

export function GetFrpStatus() {
  return window['go']['main']['App']['GetFrpStatus']();
}

export function GetFrpVersions() {
  return window['go']['main']['App']['GetFrpVersions']();
}

export function GetFrpcVersion() {
  return window['go']['main']['App']['GetFrpcVersion']();
}

export function GetMirrors() {
  return window['go']['main']['App']['GetMirrors']();
}

export function GetRootDir() {
  return window['go']['main']['App']['GetRootDir']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function ReadConfig() {
  return window['go']['main']['App']['ReadConfig']();
}

export function RestartFrp() {
  return window['go']['main']['App']['RestartFrp']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartFrp() {
  return window['go']['main']['App']['StartFrp']();
}

export function StopFrp() {
  return window['go']['main']['App']['StopFrp']();
}

export function ValidateConfig() {
  return window['go']['main']['App']['ValidateConfig']();
}

export function WriteConfig(arg1) {
  return window['go']['main']['App']['WriteConfig'](arg1);
}
