// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {frp} from '../models';
import {download} from '../models';
import {main} from '../models';
import {system} from '../models';

export function CheckFrpcInstalled():Promise<boolean>;

export function ChooseDirectory(arg1:string):Promise<string>;

export function DownloadFrpc(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function GetDownloadProgress():Promise<number>;

export function GetFrpLogs(arg1:number):Promise<string>;

export function GetFrpStatus():Promise<frp.FrpStatus>;

export function GetFrpVersions():Promise<Array<string>>;

export function GetFrpcVersion():Promise<string>;

export function GetMirrors():Promise<Array<download.Mirror>>;

export function GetRootDir():Promise<string>;

export function GetSettings():Promise<main.AppSettings>;

export function GetSystemInfo():Promise<system.SystemInfo>;

export function ReadConfig():Promise<string>;

export function RestartFrp():Promise<void>;

export function SaveSettings(arg1:main.AppSettings):Promise<main.AppSettings>;

export function StartFrp():Promise<void>;

export function StopFrp():Promise<void>;

export function ValidateConfig():Promise<string>;

export function WriteConfig(arg1:string):Promise<void>;
